# Generated by Django 5.0.6 on 2024-05-29 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField()),
                ('country', models.CharField()),
                ('condition', models.CharField()),
                ('condition_img', models.URLField(default='')),
                ('temp_f', models.FloatField(default=30)),
                ('feels_like', models.FloatField(default=30)),
                ('humidity', models.SmallIntegerField()),
                ('uv', models.SmallIntegerField()),
                ('wind_mph', models.SmallIntegerField()),
                ('wind_dir', models.CharField()),
                ('pressure_in', models.SmallIntegerField()),
                ('precip_in', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
