# Generated by Django 5.0.6 on 2024-05-22 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField()),
                ('country', models.CharField()),
                ('condition', models.CharField()),
                ('temp_c', models.FloatField()),
                ('temp_f', models.FloatField()),
                ('humidity', models.SmallIntegerField()),
                ('uv', models.SmallIntegerField()),
                ('wind_mph', models.SmallIntegerField()),
                ('wind_dir', models.CharField()),
                ('pressure_in', models.SmallIntegerField()),
                ('precip_in', models.SmallIntegerField()),
                ('observation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.observation')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
