# Generated by Django 5.0.6 on 2024-05-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourly',
            name='temp_f',
        ),
    ]
