# Generated by Django 5.0.6 on 2024-05-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0002_remove_hourly_temp_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourly',
            name='condition_img',
            field=models.URLField(default=''),
        ),
    ]
