# Generated by Django 5.0.6 on 2024-05-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0003_hourly_condition_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourly',
            name='temp_c',
        ),
        migrations.AddField(
            model_name='hourly',
            name='temp_f',
            field=models.IntegerField(default=30),
        ),
    ]
