# Generated by Django 5.0.6 on 2024-05-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0004_remove_hourly_temp_c_hourly_temp_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='date',
            field=models.DateTimeField(default='24.05.2024 18:00'),
        ),
    ]
