# Generated by Django 5.0.6 on 2024-05-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0005_alter_hourly_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourly',
            name='feels_like',
            field=models.FloatField(default=models.FloatField(default=30)),
        ),
        migrations.AlterField(
            model_name='hourly',
            name='temp_f',
            field=models.FloatField(default=30),
        ),
    ]
