# Generated by Django 5.0.6 on 2024-05-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0006_hourly_feels_like_alter_hourly_temp_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='date',
            field=models.DateTimeField(default='26.05.2024 09:00'),
        ),
    ]
