# Generated by Django 5.0.6 on 2024-05-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0007_alter_hourly_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='date',
            field=models.DateTimeField(default='26.05.2024 10:00'),
        ),
    ]
