# Generated by Django 5.0.6 on 2024-05-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0008_alter_hourly_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='date',
            field=models.DateTimeField(default='26.05.2024 11:00'),
        ),
    ]
