# Generated by Django 5.0.6 on 2024-05-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0009_alter_hourly_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='date',
            field=models.DateTimeField(default='27.05.2024 08:00'),
        ),
    ]
