# Generated by Django 4.2 on 2024-05-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_remove_observation_pressure_in_and_more'),
        ('hourly', '0010_alter_hourly_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourly',
            name='observation_id',
        ),
        migrations.AddField(
            model_name='hourly',
            name='observation',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='hourlys', to='weather.observation'),
        ),
        migrations.AlterField(
            model_name='hourly',
            name='date',
            field=models.DateTimeField(default='27.05.2024 16:00'),
        ),
    ]
