# Generated by Django 5.0.6 on 2024-05-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0010_alter_hourly_feels_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourly',
            name='feels_like',
        ),
    ]
