# Generated by Django 5.0.6 on 2024-05-27 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0010_alter_hourly_date'),
        ('weather', '0007_remove_observation_pressure_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourly',
            name='observation_id',
        ),
        migrations.AddField(
            model_name='hourly',
            name='observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hourlys', to='weather.observation'),
        ),
        migrations.AlterField(
            model_name='hourly',
            name='date',
            field=models.DateTimeField(default='27.05.2024 16:00'),
        ),
    ]
