# Generated by Django 4.2 on 2024-05-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_remove_observation_pressure_in_and_more'),
        ('hourly', '0011_remove_hourly_observation_id_hourly_observation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='observation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hourlys', to='weather.observation'),
        ),
    ]
