# Generated by Django 5.0.6 on 2024-05-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0011_remove_hourly_feels_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourly',
            name='feels_like',
            field=models.FloatField(default=30),
        ),
    ]
