# Generated by Django 5.0.6 on 2024-05-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0011_remove_hourly_observation_id_hourly_observation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourly',
            old_name='observation',
            new_name='observation_id',
        ),
    ]
