# Generated by Django 5.0.6 on 2024-05-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0012_rename_observation_hourly_observation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='date',
            field=models.DateTimeField(default='27.05.2024 20:00'),
        ),
    ]
