# Generated by Django 4.2 on 2024-05-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0012_alter_hourly_observation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourly',
            old_name='observation',
            new_name='observation_id',
        ),
    ]
