# Generated by Django 5.0.6 on 2024-05-28 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0013_alter_hourly_date_remove_hourly_observation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourly',
            name='observation_id',
        ),
    ]
