# Generated by Django 4.2 on 2024-05-27 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_remove_observation_pressure_in_and_more'),
        ('hourly', '0014_alter_hourly_observation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hourlys', to='weather.observation'),
        ),
    ]
