# Generated by Django 5.0.6 on 2024-05-28 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0013_alter_hourly_date'),
        ('hourly', '0014_remove_hourly_observation_id'),
    ]

    operations = [
    ]
