# Generated by Django 4.2 on 2024-05-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0015_alter_hourly_observation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourly',
            old_name='observation_id',
            new_name='observation',
        ),
    ]
