<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-28 14:33
=======
# Generated by Django 4.2 on 2024-05-28 12:23
>>>>>>> 40148ec85511fdd7e4baed4d647d5b0d90931e24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0015_merge_20240527_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='date',
<<<<<<< HEAD
            field=models.DateTimeField(default='28.05.2024 14:00'),
=======
            field=models.DateTimeField(default='28.05.2024 12:00'),
>>>>>>> 40148ec85511fdd7e4baed4d647d5b0d90931e24
        ),
    ]
