# Generated by Django 5.0.6 on 2024-05-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0015_merge_20240527_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='date',
            field=models.DateTimeField(default='28.05.2024 12:00'),
        ),
    ]
