# Generated by Django 5.0.6 on 2024-05-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0016_alter_hourly_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='date',
            field=models.DateTimeField(default='28.05.2024 15:00'),
        ),
    ]
