<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-28 15:17
=======
# Generated by Django 5.0.6 on 2024-05-28 18:35
>>>>>>> 40148ec85511fdd7e4baed4d647d5b0d90931e24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0016_alter_hourly_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='date',
<<<<<<< HEAD
            field=models.DateTimeField(default='28.05.2024 15:00'),
=======
            field=models.DateTimeField(default='28.05.2024 18:00'),
>>>>>>> 40148ec85511fdd7e4baed4d647d5b0d90931e24
        ),
    ]
