# Generated by Django 5.0.6 on 2024-05-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0017_alter_hourly_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='date',
            field=models.DateTimeField(default='28.05.2024 19:00'),
        ),
    ]
