# Generated by Django 5.0.6 on 2024-05-29 00:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0018_alter_hourly_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
