# Generated by Django 4.2 on 2024-05-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0002_remove_observation_max_c_remove_observation_min_c_and_more'),
        ('hourly', '0019_alter_hourly_date'),
    ]

    operations = [
    ]
