# Generated by Django 5.0.6 on 2024-05-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hourly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField()),
                ('country', models.CharField()),
                ('condition', models.CharField()),
                ('condition_img', models.URLField(default='')),
                ('humidity', models.SmallIntegerField()),
                ('max_f', models.FloatField()),
                ('min_f', models.FloatField()),
                ('wind_mph', models.SmallIntegerField()),
                ('precip_in', models.SmallIntegerField()),
                ('sunrise', models.DateTimeField()),
                ('sunset', models.DateTimeField()),
                ('moonrise', models.DateTimeField()),
                ('moonset', models.DateTimeField()),
                ('moon_phase', models.CharField()),
                ('uv', models.SmallIntegerField(default=1)),
                ('note', models.CharField(default='todays notes...')),
                ('hourlys', models.ManyToManyField(to='hourly.hourly')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
