# Generated by Django 5.0.6 on 2024-05-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_observation_max_c_remove_observation_min_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='condition_img',
            field=models.URLField(default='null'),
            preserve_default=False,
        ),
    ]
