# Generated by Django 5.0.6 on 2024-05-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_observation_condition_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='max_f',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='observation',
            name='min_f',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='observation',
            name='temp_f',
            field=models.IntegerField(),
        ),
    ]
