# Generated by Django 5.0.6 on 2024-05-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_observation_max_f_alter_observation_min_f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='max_f',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='observation',
            name='min_f',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='observation',
            name='temp_f',
            field=models.FloatField(),
        ),
    ]
