# Generated by Django 5.0.6 on 2024-05-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_observation_max_f_alter_observation_min_f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='condition_img',
            field=models.URLField(default=''),
        ),
    ]
