# Generated by Django 5.0.6 on 2024-05-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_alter_observation_condition_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='pressure_in',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='temp_f',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='wind_dir',
        ),
    ]
