# Generated by Django 5.0.6 on 2024-05-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_remove_observation_pressure_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='note',
            field=models.CharField(default=''),
        ),
    ]
