# Generated by Django 5.0.6 on 2024-05-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly', '0014_remove_hourly_observation_id'),
        ('weather', '0008_observation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='hourlys',
            field=models.ManyToManyField(to='hourly.hourly'),
        ),
    ]
