<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-29 18:39
=======
# Generated by Django 4.2 on 2024-05-29 14:39
>>>>>>> huiwen_mac

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_observation_hourlys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='note',
            field=models.CharField(default='todays notes...'),
        ),
    ]
