# Generated by Django 5.0.6 on 2024-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_observation_hourlys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='note',
            field=models.CharField(default='todays notes...'),
        ),
    ]
