# Generated by Django 5.0.6 on 2024-05-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_alter_observation_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='hourlys',
        ),
    ]
